## 추론 기반 기법과 신경망

### 신경망에서의 단어 처리

In [2]:
import numpy as np

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7,3)
h = np.matmul(c, W)
print(W[0])
print(h)

[1.48291755 1.85118632 0.01369802]
[[1.48291755 1.85118632 0.01369802]]


In [3]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.params
        out = np.dot(x, W)
        self.x = x
        return out

    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [7]:
import sys
sys.path.append('..')
import numpy as np
from common.layers import MatMul

c = np.array([[1, 0, 0, 0, 0, 0, 0]])
W = np.random.randn(7, 3)
layer = MatMul(W)
h = layer.forward(c)
print(W[0])
print(h)

[ 0.4021975  -0.62560976 -1.16420722]
[[ 0.4021975  -0.62560976 -1.16420722]]
