### Embedding 계층 구현

In [4]:
import numpy as np
W = np.arange(21).reshape(7, 3)
x = np.array([1,0,0,0,0,0,0])
print(W)
h = np.dot(x, W)
print(h)
print(W[0])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
[0 1 2]
[0 1 2]


In [5]:
W[2]

array([6, 7, 8])

In [6]:
W[5]

array([15, 16, 17])

In [7]:
idx = np.array([1, 0, 3, 0]) # you say goodbye and i say hello .
W[[1,0,3,0]]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [26]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None    
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         for i, word_id in enumerate(self.idx):
#             dW[word_id] += dout[i]
#         return None
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         dW[self.idx] = dout
#         return None    

In [27]:
embed = Embedding(W)
out = embed.forward([1,0,3,0])
print(embed.idx)
print(out)

[1, 0, 3, 0]
[[ 3  4  5]
 [ 0  1  2]
 [ 9 10 11]
 [ 0  1  2]]


In [28]:
dout = np.array([[1,1,1],
                 [2,2,2],
                 [3,3,3],
                 [4,4,4]])
embed.backward(dout)
embed.grads

[array([[6, 6, 6],
        [1, 1, 1],
        [0, 0, 0],
        [3, 3, 3],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])]

In [7]:
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        dW[self.idx] = dout
        return None

In [8]:
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        for i, word_id in enumerate(self.idx):
            dW[word_id] += dout[i]
        return None

In [9]:
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

In [25]:
dW = np.zeros(5)
idx = np.array([0,1,2,0])
np.add.at(dW, idx, 1)
print(dW)

[2. 1. 1. 0. 0.]
